### ISSUE TITLE
v1 Release Plan

### ISSUE THREAD

**Issue by cmboling** [github/ghas-jira-integration#19]
#### Part one
- [x] Test, approve and merge https://github.com/github/codescanning-jira-integration/pull/15
- [x] Rename default branch to main
- [x] Retain dummy “master” branch to accommodate existing workflows referencing this branch
- [x] Notify known users using this workflow for breaking changes
    - [x] https://github.com/github/codescanning-jira-integration/issues/16

#### Part two
- [x] Update README.md
- [x] Rename repository
- [x] Release v1 tag
- [x] Smoke test v1 tag
- [x] Delete dummy master branch
- [x] Notify users to use v1 

#### Postponed to minor release (starting week of October 18)
- [ ] Refactor/Improve codebase
    - [x] https://github.com/github/codescanning-jira-integration/issues/17
    - [ ] https://github.com/github/codescanning-jira-integration/issues/18

**Comment by cmboling** [comment]
[Secret scanning alerts](https://github.com/github/codescanning-jira-integration/pull/7) will be a part of v2, which will have a separate release issue.

**Comment by cmboling** [comment]
v1 will be released this Thursday, 3 PM PST.
